#!/usr/bin/env bash

export HOSTNAME="$(hostname -s)"

BATCHTSOCMDDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"

export BATCHTSOCMDDIR

source setenv
rc=$?
if [ $rc -gt 0 ]; then
    exit $rc
fi

python3 -m pip install -e ".[dev]"
rc=$?
if [ $rc -gt 0 ]; then
    echo "pip install failed. rc $rc" >&2
    exit $rc
fi
gmake test
rc=$?
if [ $rc -gt 0 ]; then
    echo "gmake failed. rc $rc" >&2
else
    echo "gmake succeeded."
fi
exit $rc
